# Generated by Django 4.1.7 on 2023-04-16 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('cni', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cne', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('nbrEtudiant', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.enseignant')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.formation')),
            ],
        ),
        migrations.CreateModel(
            name='Inscri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.cour')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.etudiant')),
            ],
        ),
        migrations.AddField(
            model_name='etudiant',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.formation'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.group'),
        ),
        migrations.AddField(
            model_name='cour',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.module'),
        ),
    ]
