# Generated by Django 4.1.7 on 2023-04-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignant',
            old_name='cni',
            new_name='cin',
        ),
    ]
