# Generated by Django 4.1.7 on 2023-03-25 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_cour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.cour')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.etudiant')),
            ],
        ),
    ]
