# Generated by Django 4.2 on 2023-04-29 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_rename_format_cour_formation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cour',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.formation'),
        ),
        migrations.DeleteModel(
            name='Inscri',
        ),
    ]
