# Generated by Django 4.2 on 2023-05-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0004_alter_cour_formation_delete_inscri'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='username',
            field=models.CharField(default='', max_length=30),
        ),
    ]
