# Generated by Django 4.2 on 2023-05-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0006_etudiant_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
    ]
