# Generated by Django 4.2 on 2023-05-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_module_nbrcour_alter_etudiant_username'),
        ('elearning', '0009_contenu'),
    ]

    operations = [
    ]
