# Generated by Django 4.0.4 on 2023-05-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_merge_20230505_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='username',
            field=models.CharField(default='', max_length=30, unique='true'),
        ),
    ]
