# Generated by Django 4.0.4 on 2023-05-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0011_alter_etudiant_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenu',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
