# Generated by Django 4.0.4 on 2023-05-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0012_alter_contenu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cour',
            name='field_name',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
