# Generated by Django 4.0.4 on 2023-05-08 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0013_cour_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='username',
            field=models.CharField(default='', max_length=30, unique='true'),
        ),
    ]
